config/routes.rb
Wagering::Application.routes.draw do

  root :to => "pages#index"
  %w{rules terms}.each do |page|
    match "/#{page}", :to => "pages##{page}"
  end

  resources :bets

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def caption(title, header = title)
    @title, @header = title, header
  end
end

app/views/bets/index.html.haml
- phrases = ['Election sucks', 'Britney Spears', 'Pease in the middle east', 'Chicago Bulls', 'Honda Cvic', 'Google is down', 'Hurricane', 'Recession']
.bets
  - 30.times do |n|
    .bet{:class => [n%3==0 && :negative]}
      .phrase= phrases[rand(phrases.length)]
      .site
        %a{:href=>bet_path(1)}
          = "site#{n}example.com"
      .description
        Neque porro quisquam est qui dolorem ipsum quia dolor sit amet
      .time-remaining
        1 day, 3 hours

- content_for :context do
  = link_to 'Start a new one', new_bet_path

app/views/bets/new.html.haml
.new-bet
  %form(action='#')
    %fieldset
      %legend Start a new bet

      %label(for='description') I want to bet because
      %input(id='description' type='text' maxlength='200' value='I saw UFO')

      %label(for='phrase') And think the phrase
      %input(id='phrase' maxlength='50' value='UFO has settled')

      %label(for='url') Will be on (web site)
      %input(id='url' type='url' value='http://news.com')

      %label(for='points') so I can win points more than
      %input(id='points' type='numeric' value='50')

      %input(type='submit' value='Rock & Roll!')

app/views/bets/show.html.haml
.bet
  .description The election campaign sucks as Tonny with Gillard do
  .price 250 points
  .phrase Election sucks
  .time-remaining 1 day, 3 hours approx

.prediction
  .supporter Winner of supporter will get 300 points
  .taker Winner of takers will get 450 points

.participants
  - 7.times do |n|
    .participant{:class => (n%3) == 0 ? 'mine' : nil}
      .name= "user#{n}"
      .price= "#{n%2==0?'+':'-'} #{n*rand(50)}"

.participate
  %form(action='#')
    %fieldset
      %legend Participate
      %label(for='points') Points
      %input(id='points' type='number' value='260')
      %input(type='submit' value='Take the bet!')
      %input(type='submit' value='Support the bet!')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= "#{@title && (@title + ' - ')}Social Wagering"
    = stylesheet_link_tag
    = javascript_include_tag :defaults
    %meta(charset='UTF-8')
    %meta(name="description" content="Social Wagering - bet on the content of web pages")
    %meta(name="keywords" content="Web bets, online wagering, site bets, page bets, site bets, social wagering")
    %meta(name="author" content="Dmytrii Nagirniak, Dmitriy Nagirnyak")

    = stylesheet_link_tag 'main'
    %script(src='http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js')
    /[if lt IE 9]
      %script(src="http://html5shiv.googlecode.com/svn/trunk/html5.js")
    = javascript_include_tag :defaults
    = csrf_meta_tag
  %body
    #container
      %header
        %h1
          %a{:href=>root_path}
            %img{:src=>image_path("logo.png"), :alt=>'Social Wagering - Home'}
          %span.slogan
            Bet the Web!
        %nav
          %a{:href=>rules_path} Rules
          %a{:href=>terms_path} Terms
          %a{:href=>bets_path} Bets
      %section#content
        - if @header
          %h1.caption= @header
        #main
          = yield
        #context= yield(:context)
        .clear
      %footer
        %a{:href=>root_path} Home
        %a{:href=>rules_path} Rules
        %a{:href=>terms_path} Terms
        %a{:href=>bets_path} Bets

app/views/pages/index.html.haml
Online social Wagering Web site allows to to make bets on the content of web pages.
Some example may be:
%ul
  %li Celebrity news (I bet that news.com will have something about Britney Spears).
  %li Politics (I bet that first page of google search for 'Debt' will contain 'Obama').
  %li Microblogging (I bet the there will be tweets about Melbourne in the @best-city tag).
  %li and so on... only the sky is the limit.

- content_for :context do
  %h3
    Action points
  %nav
    %a(href='#') Create your bet
    %a(href='#') Participate

app/views/pages/rules.html.haml
- caption 'Rules'
%p
  The basics are:
  %ul
    %li Any user can start a new bet
    %li Any user can take or suppoer other bets (participate)
    %li There is only one winner
    %li
      The winner takes all the points from the opposite group.
      So if you took the bet and won, you get all the points from all supporters.
      If you supported the bet and won, you get all the points from all takers.
    %li The winner is the person who has the highest bid and guesses the result correctly.
    %li All other people who guess the result correctly get all of the points back.

app/views/pages/terms.html.haml
- caption 'Terms & Conditions'
%p
  Just do not abuse :)